# This is a boilerplate parameters config generated for pipeline 'finetuning'
# using Kedro 1.0.0.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/1.0.0/configuration/parameters.html

finetuning:
  logistic_regression:
    C: [0.01, 0.1, 1, 10]
    solver: ["liblinear", "lbfgs"]
  decision_tree:
    max_depth: [null, 5, 10, 20]
    min_samples_split: [2, 5, 10]
  random_forest:
    n_estimators: [100, 200, 300]
    max_depth: [null, 5, 10, 20]
  lightgbm:
    num_leaves: [31, 50, 100]
    learning_rate: [0.01, 0.05, 0.1]
    n_estimators: [50, 100, 200]
  xgboost:
    max_depth: [3, 5, 7]
    learning_rate: [0.01, 0.05, 0.1]
    n_estimators: [50, 100, 200]
